#pragma once
#include <Arduino.h>

/**
 * @brief Logical button identifiers.
 * Used to reference each button in the system.
 */
enum ButtonId {
    BTN_OPEN,       ///< Button to open the cover
    BTN_CLOSE,      ///< Button to close the cover
    BTN_LIGHT_ON,   ///< Button to turn the light on
    BTN_LIGHT_OFF,  ///< Button to turn the light off
    BUTTON_COUNT    ///< Total number of buttons
};

/**
 * @brief Event types generated by the debouncer.
 * Represents the possible states or actions for a button.
 */
enum ButtonEvent {
    BUTTON_NONE,      ///< No event
    BUTTON_PRESSED,   ///< Button was pressed
    BUTTON_RELEASED,  ///< Button was released
    BUTTON_CLICK      ///< Button was clicked (short press)
};

/**
 * @brief Initializes all button inputs and debouncing logic.
 */
void initButtons();

/**
 * @brief Updates the button states and processes debouncing.
 * Should be called regularly in the main loop.
 */
void updateButtons();

/**
 * @brief Checks if the specified button was pressed.
 * @param id Logical button identifier.
 * @return true if the button was pressed, false otherwise.
 */
bool buttonPressed(ButtonId id);

/**
 * @brief Checks if the specified button was released.
 * @param id Logical button identifier.
 * @return true if the button was released, false otherwise.
 */
bool buttonReleased(ButtonId id);

/**
 * @brief Checks if the specified button was clicked (short press).
 * @param id Logical button identifier.
 * @return true if the button was clicked, false otherwise.
 */
bool buttonClicked(ButtonId id);

/**
 * @brief Checks if the specified button is currently held down.
 * @param id Logical button identifier.
 * @return true if the button is down, false otherwise.
 */
bool buttonIsDown(ButtonId id);

// --- POTI ---

/**
 * @brief Updates the potentiometer value.
 * Should be called regularly to read the current brightness setting.
 */
void updatePoti();

/**
 * @brief Gets the current brightness value from the potentiometer.
 * @return Brightness value (0–255).
 */
uint8_t getPotiBrightness();

/**
 * @brief Updates the panel brightness, if panel was switched on
 * @return void
 */
void handlePotiBrightness();